name: Update Data

on:
  schedule:
    # update every week on Monday
    - cron: "0 0 * * 1"
  # manual trigger
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run download_data.py
        run: python download_data.py

      - name: Run chunk_data.py
        run: python chunk_data.py

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: updated data
